sudo: required
services:
  - docker

before_install:
  - docker build -t rubenberna/react-test -f ./web/Dockerfile.dev ./web

script:
  - docker run -e CI=true rubenberna/react-test npm run test -- --coverage

after_success:
  - docker build -t rubenberna/salesforce-scheduler-nginx ./nginx
  - docker build -t rubenberna/salesforce-scheduler-server ./server
  - docker build -t rubenberna/salesforce-scheduler-web ./web
  #login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push rubenberna/salesforce-scheduler-nginx
  - docker push rubenberna/salesforce-scheduler-server
  - docker push rubenberna/salesforce-scheduler-web

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "salesforce-scheduler"
  env: "SalesforceScheduler-env-1"
  bucket_name: "elasticbeanstalk-eu-west-1-305799247952"
  bucket_path: "salesforce-scheduler"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
