sudo: required
services:
  - docker

before_install:
  - docker build -t rubenberna/react-test -f ./web/Dockerfile.dev ./web

script:
  - docker run -e CI=true rubenberna/react-test npm run test -- --coverage

after_success:
  - docker build -t rubenberna/salesforce-scheduler-nginx ./nginx
  - docker build -t rubenberna/salesforce-scheduler-server ./server
  - docker build -t rubenberna/salesforce-scheduler-web ./web
  #login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push rubenberna/salesforce-scheduler-nginx
  - docker push rubenberna/salesforce-scheduler-server
  - docker push rubenberna/salesforce-scheduler-web
